### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by whimsica** [ccc-tomr/Dullahan#1]
I would like to try this solution, because I am getting the same grey screen with X in it,
but am stuck on the instructions. I'm not sure how to get the installer to my ec2 instance.

I am connected to the ec2 instance through ssh.

How do I copy over the installer to the ec2 instance.
Do I use something like wget ? What would the address be?

//after I get it onto the computer would I do this?
sudo gdebi installer/ubuntu1404/dullahan_1.0_amd64.deb

Thanks,
Dan

**Comment by ccc-tomr** [comment]
Hi Dan,

sorry for the late response, you probably already solved the issue but I will address it anyway for anybody who gets stuck moving the installer onto their cloud instance.

1) Download the [Dullahan installer](https://github.com/ccc-tomr/Dullahan/blob/master/installer/ubuntu1404/dullahan_1.0_amd64.deb) onto your local computer

2) use scp to copy the installer from your local computer to your cloud instance:
scp -i <key file> <Dullahan-file on your computer> <cloudlogin>@<ip-address of your cloud instance>:<installer destination>

i.e. scp -i myKey.pem Downloads/dullahan_1.0_amd64.deb ubuntu@123.45.67.89:~
(this will copy the Dullahan file into the home folder of your ubuntu account on the cloud instance)

3) follow the install instruction in the [Dullahan manual](https://github.com/ccc-tomr/Dullahan#how-to-use-the-dullahan-installer)

I hope this helps anyone who gets stuck. 

One comment: If you are dealing with cloud instances, you should know how to get files on and off with scp, this should be considered basic knowledge. 

Closing
