### ISSUE TITLE
Any plan to update it for Ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by pabloa** [ccc-tomr/Dullahan#2]
Hello

Is there any plan to update it for Ubuntu 16.04 LTS?

**Comment by ccc-tomr** [comment]
Definitely, I just need a bit of time. Did you try 16.04 already  ? If yes, what kind of issues did you run into ? 
Thanks

**Comment by pabloa** [comment]
Systemd lol.

Most of the errors in my scripts (of any kind, for any system) are
generated because they are not working correctly with systemd.

I am migrating them slowly though.

**Comment by ccc-tomr** [comment]
Ahhh that's right, systemd vs. upstart... Well I am going through this transition in another project, so should be able to do it for dullahan shortly after that, I'll keep you posted

**Comment by ccc-tomr** [comment]
Tested on Ubuntu 16.04 LTS and works without modifications.
